export const STATUS_SELECT = [
  { label: '01', value: '01' },
  { label: '02', value: '02' },
  { label: '03', value: '03' },
  { label: '04', value: '04' },
  { label: '05', value: '05' },
];

export const GROUP_SELECT = [
  { label: 'AVENGERS', value: 'AVENGERS' },
  { label: 'BIRDS OF PREY', value: 'BIRDS OF PREY' },
  { label: 'DEFENDERS', value: 'DEFENDERS' },
  { label: 'FANTASTIC FOUR', value: 'FANTASTIC FOUR' },
  { label: 'GUARDIANS OF GALAXY', value: 'GUARDIANS OF GALAXY' },
  { label: 'INHUMAN', value: 'INHUMAN' },
  { label: 'INJUSTICE', value: 'INJUSTICE' },
  { label: 'JUSTICE LEAGUE', value: 'JUSTICE LEAGUE' },
  { label: 'LANTERN CORPS', value: 'LANTERN CORPS' },
  { label: 'X-MEN', value: 'X-MEN' },
];

export const dummyData = [
  {
    username: 'captain.america',
    firstName: 'Steve',
    lastName: 'Rogers',
    email: 'steve.rogers@shield.org',
    birthDate: new Date(-1625123232 * 1000),
    basicSalary: 0,
    status: '01',
    group: 'AVENGERS',
    description: 'The first avenger',
  },
  {
    username: 'the_ironman',
    firstName: 'Tony',
    lastName: 'Stark',
    email: 'tony@stark.co.us',
    birthDate: new Date(12829269 * 1000),
    basicSalary: 9999999,
    status: '01',
    group: 'AVENGERS',
    description: 'CEO of Stark Industries',
  },
  {
    username: 'odinson777',
    firstName: 'Thor',
    lastName: 'Odinson',
    email: 'thor@asgardmail.com',
    birthDate: new Date(-2208988800 * 1000),
    basicSalary: 777000,
    status: '03',
    group: 'AVENGERS',
    description: 'God of thunder',
  },
  {
    username: 'dark_knight',
    firstName: 'Bruce',
    lastName: 'Wayne',
    email: 'batman@waynetech.co.us',
    birthDate: new Date(260538069 * 1000),
    basicSalary: 13543132415,
    status: '03',
    group: 'JUSTICE LEAGUE',
    description: 'Protector of Gotham City',
  },
  {
    username: 'thething',
    firstName: 'Ben',
    lastName: 'Grimm',
    email: 'thething@rocketmail.com',
    birthDate: new Date(571881600 * 1000),
    basicSalary: 15000,
    status: '03',
    group: 'FANTASTIC FOUR',
    description: 'Spacecraft pilot',
  },
  {
    username: 'bukan.wonderwoman.mu',
    firstName: 'Diana',
    lastName: 'Prince',
    email: 'wonderwoman@gmail.com',
    birthDate: new Date(-908236800 * 1000),
    basicSalary: 565465,
    status: '02',
    group: 'JUSTICE LEAGUE',
    description: 'Amazons',
  },
  {
    username: 'nwywebcrawler',
    firstName: 'Peter',
    lastName: 'Parker',
    email: 'spidey@hotmail.com',
    birthDate: new Date(998092800 * 1000),
    basicSalary: 100,
    status: '03',
    group: 'AVENGERS',
    description: 'Your friendly neighbourhood',
  },
  {
    username: 'cryptonite.addict',
    firstName: 'Alexander',
    lastName: 'Luthor',
    email: 'lex@luthor.com',
    birthDate: new Date(338947200 * 1000),
    basicSalary: 8888899966,
    status: '05',
    group: 'INJUSTICE',
    description: 'Bald',
  },
  {
    username: 'wolverine',
    firstName: 'James',
    lastName: 'Howlett',
    email: 'logan88@gmail.com',
    birthDate: new Date(-4354905600 * 1000),
    basicSalary: 2000,
    status: '03',
    group: 'X-MEN',
    description: 'Amnesia',
  },
  {
    username: 'strongest.avenger',
    firstName: 'Bruce',
    lastName: 'Banner',
    email: 'always.angry@outlook.com',
    birthDate: new Date(-1209600 * 1000),
    basicSalary: 50500,
    status: '01',
    group: 'AVENGERS',
    description: 'The Incredible Hulk',
  },
  {
    username: 'mulan.hua',
    firstName: 'Hua',
    lastName: 'Mulan',
    email: 'huamulan1907@yahoo.com',
    birthDate: new Date(900848469 * 1000),
    basicSalary: 5000,
    status: '02',
    group: 'OTHERS',
    description: 'LOREM IPSUM DOLOR SIT AMET',
  },
];
