export const dummyData2 = [
  {
    username: 'mus.',
    firstName: 'Hiroko',
    lastName: 'Patrick',
    email: 'risus.Nulla@eratsemperrutrum.net',
    birthDate: '471970525',
    basicSalary: 8530347,
    status: '04',
    group: 'X-MEN',
    description: 'Integer aliquam adipiscing lacus. Ut nec urna',
  },
  {
    username: 'ligula',
    firstName: 'Cathleen',
    lastName: 'Odonnell',
    email: 'Etiam@estMauris.co.uk',
    birthDate: '750401439',
    basicSalary: 6578854,
    status: '05',
    group: 'DEFENDERS',
    description: 'aliquet diam. Sed diam lorem, auctor quis,',
  },
  {
    username: 'turpis.',
    firstName: 'Herman',
    lastName: 'Hewitt',
    email: 'sapien.Nunc@diamPellentesque.ca',
    birthDate: '348621306',
    basicSalary: 8335016,
    status: '03',
    group: 'INHUMAN',
    description:
      'tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla.',
  },
  {
    username: 'sed',
    firstName: 'Tobias',
    lastName: 'Petty',
    email: 'iaculis.quis.pede@Morbi.edu',
    birthDate: '612665754',
    basicSalary: 6127624,
    status: '01',
    group: 'X-MEN',
    description: 'lectus quis',
  },
  {
    username: 'et,',
    firstName: 'Angela',
    lastName: 'Ross',
    email: 'Maecenas@pedeblanditcongue.edu',
    birthDate: '399495024',
    basicSalary: 6637704,
    status: '05',
    group: 'FANTASTIC FOUR',
    description: 'mauris sapien, cursus in, hendrerit consectetuer, cursus',
  },
  {
    username: 'Quisque',
    firstName: 'Abigail',
    lastName: 'Reed',
    email: 'eu@elementumpurusaccumsan.net',
    birthDate: '1107579403',
    basicSalary: 9105492,
    status: '02',
    group: 'DEFENDERS',
    description: 'ut aliquam iaculis, lacus pede sagittis augue, eu',
  },
  {
    username: 'eget',
    firstName: 'Benjamin',
    lastName: 'Talley',
    email: 'nunc.ac@tinciduntaliquamarcu.edu',
    birthDate: '584958189',
    basicSalary: 2610210,
    status: '05',
    group: 'LANTERN CORPS',
    description: 'mi. Duis risus odio, auctor vitae, aliquet',
  },
  {
    username: 'aliquet.',
    firstName: 'Camilla',
    lastName: 'Durham',
    email: 'Donec@ridiculusmus.org',
    birthDate: '808059356',
    basicSalary: 6975749,
    status: '01',
    group: 'X-MEN',
    description: 'Fusce mi lorem, vehicula et, rutrum',
  },
  {
    username: 'erat.',
    firstName: 'Isaiah',
    lastName: 'Wolfe',
    email: 'rhoncus@orciUtsagittis.net',
    birthDate: '248018675',
    basicSalary: 4552272,
    status: '03',
    group: 'BIRDS OF PREY',
    description: 'velit',
  },
  {
    username: 'Fusce',
    firstName: 'Kato',
    lastName: 'Avery',
    email: 'magna.Cras@vel.ca',
    birthDate: '1035395032',
    basicSalary: 9531676,
    status: '02',
    group: 'DEFENDERS',
    description: 'lectus quis massa. Mauris',
  },
  {
    username: 'nibh',
    firstName: 'Rajah',
    lastName: 'Lee',
    email: 'ligula.Nullam.feugiat@sollicitudin.net',
    birthDate: '1026358520',
    basicSalary: 5858452,
    status: '01',
    group: 'DEFENDERS',
    description: 'mauris id sapien. Cras dolor',
  },
  {
    username: 'Duis',
    firstName: 'Anastasia',
    lastName: 'Morse',
    email: 'per@anunc.co.uk',
    birthDate: '694083162',
    basicSalary: 3214759,
    status: '04',
    group: 'INJUSTICE',
    description: 'eget odio.',
  },
  {
    username: 'non',
    firstName: 'Brent',
    lastName: 'Sargent',
    email: 'libero@ac.com',
    birthDate: '758309128',
    basicSalary: 535680,
    status: '03',
    group: 'FANTASTIC FOUR',
    description: 'eget, venenatis a, magna. Lorem ipsum dolor sit amet,',
  },
  {
    username: 'purus.',
    firstName: 'Lawrence',
    lastName: 'Mercado',
    email: 'venenatis@vulputateposuerevulputate.co.uk',
    birthDate: '649901388',
    basicSalary: 2132057,
    status: '01',
    group: 'DEFENDERS',
    description: 'Nunc commodo auctor velit. Aliquam nisl. Nulla eu',
  },
  {
    username: 'Curabitur',
    firstName: 'Justin',
    lastName: 'Richards',
    email: 'diam@Curabiturvel.net',
    birthDate: '232932363',
    basicSalary: 9359618,
    status: '02',
    group: 'BIRDS OF PREY',
    description: 'senectus et netus et malesuada fames ac turpis',
  },
  {
    username: 'viverra.',
    firstName: 'Peter',
    lastName: 'Hill',
    email: 'per.inceptos.hymenaeos@velitduisemper.edu',
    birthDate: '1094465288',
    basicSalary: 9459759,
    status: '05',
    group: 'X-MEN',
    description: 'orci. Phasellus dapibus',
  },
  {
    username: 'fermentum',
    firstName: 'Rinah',
    lastName: 'Delaney',
    email: 'Cum.sociis@nonvestibulum.ca',
    birthDate: '1022962292',
    basicSalary: 1903927,
    status: '02',
    group: 'GUARDIANS OF GALAXY',
    description: 'tellus. Nunc lectus',
  },
  {
    username: 'ultricies',
    firstName: 'Fleur',
    lastName: 'Bradshaw',
    email: 'egestas.lacinia.Sed@Nullamscelerisqueneque.co.uk',
    birthDate: '211985299',
    basicSalary: 7094613,
    status: '03',
    group: 'JUSTICE LEAGUE',
    description: 'Donec vitae erat vel pede blandit congue.',
  },
  {
    username: 'eu',
    firstName: 'Brenda',
    lastName: 'Mcguire',
    email: 'libero.Integer.in@consectetuerrhoncusNullam.edu',
    birthDate: '571939315',
    basicSalary: 9070339,
    status: '02',
    group: 'FANTASTIC FOUR',
    description: 'Nunc ut erat. Sed nunc',
  },
  {
    username: 'vestibulum',
    firstName: 'Alfonso',
    lastName: 'Bean',
    email: 'dictum.eu@tellusNunclectus.edu',
    birthDate: '480466062',
    basicSalary: 1094787,
    status: '02',
    group: 'BIRDS OF PREY',
    description:
      'nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque',
  },
  {
    username: 'Donec',
    firstName: 'Wyoming',
    lastName: 'Matthews',
    email: 'fermentum.risus@sodalesatvelit.org',
    birthDate: '826459757',
    basicSalary: 2699486,
    status: '01',
    group: 'JUSTICE LEAGUE',
    description: 'eget',
  },
  {
    username: 'fermentum',
    firstName: 'Philip',
    lastName: 'Aguirre',
    email: 'augue.malesuada@auctor.edu',
    birthDate: '983520708',
    basicSalary: 6079295,
    status: '01',
    group: 'INJUSTICE',
    description: 'mauris eu elit. Nulla',
  },
  {
    username: 'Duis',
    firstName: 'Penelope',
    lastName: 'Pierce',
    email: 'molestie.dapibus.ligula@et.ca',
    birthDate: '120228524',
    basicSalary: 3918737,
    status: '04',
    group: 'DEFENDERS',
    description: 'Mauris eu turpis. Nulla aliquet.',
  },
  {
    username: 'ac',
    firstName: 'Demetrius',
    lastName: 'Rhodes',
    email: 'elementum@necmetus.net',
    birthDate: '316588894',
    basicSalary: 7944640,
    status: '02',
    group: 'FANTASTIC FOUR',
    description: 'ac tellus. Suspendisse sed',
  },
  {
    username: 'fermentum',
    firstName: 'Rhea',
    lastName: 'Benson',
    email: 'lorem.lorem@Morbi.edu',
    birthDate: '281624926',
    basicSalary: 3920163,
    status: '03',
    group: 'BIRDS OF PREY',
    description: 'a, scelerisque sed, sapien.',
  },
  {
    username: 'aliquet.',
    firstName: 'Hilda',
    lastName: 'Suarez',
    email: 'a.magna@sitamet.net',
    birthDate: '851628950',
    basicSalary: 4211892,
    status: '05',
    group: 'BIRDS OF PREY',
    description: 'Suspendisse sagittis. Nullam',
  },
  {
    username: 'eget',
    firstName: 'Vielka',
    lastName: 'Mills',
    email: 'Nulla.facilisis.Suspendisse@lectus.co.uk',
    birthDate: '107068593',
    basicSalary: 7896547,
    status: '03',
    group: 'JUSTICE LEAGUE',
    description: 'semper, dui lectus rutrum urna, nec luctus felis purus ac',
  },
  {
    username: 'ut',
    firstName: 'Wyatt',
    lastName: 'Foster',
    email: 'ullamcorper.viverra@rhoncusProin.com',
    birthDate: '397172741',
    basicSalary: 2436057,
    status: '03',
    group: 'FANTASTIC FOUR',
    description:
      'semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam',
  },
  {
    username: 'Duis',
    firstName: 'Marshall',
    lastName: 'Duffy',
    email: 'convallis.convallis@acorci.ca',
    birthDate: '144535514',
    basicSalary: 6076615,
    status: '01',
    group: 'AVENGERS',
    description: 'massa. Vestibulum accumsan neque et nunc. Quisque',
  },
  {
    username: 'mus.',
    firstName: 'April',
    lastName: 'Davidson',
    email: 'lobortis.quis@pellentesque.edu',
    birthDate: '253589090',
    basicSalary: 4425295,
    status: '05',
    group: 'DEFENDERS',
    description: 'sem.',
  },
  {
    username: 'mattis.',
    firstName: 'Malcolm',
    lastName: 'Kirk',
    email: 'velit@accumsan.org',
    birthDate: '697697382',
    basicSalary: 5324416,
    status: '04',
    group: 'INHUMAN',
    description: 'non,',
  },
  {
    username: 'eros.',
    firstName: 'Marny',
    lastName: 'Medina',
    email: 'consequat@dolor.net',
    birthDate: '497342013',
    basicSalary: 8517885,
    status: '02',
    group: 'BIRDS OF PREY',
    description: 'et netus et malesuada fames ac turpis egestas. Fusce',
  },
  {
    username: 'ipsum',
    firstName: 'Erica',
    lastName: 'Stout',
    email: 'vel.nisl.Quisque@turpisegestas.net',
    birthDate: '173145322',
    basicSalary: 4391239,
    status: '01',
    group: 'GUARDIANS OF GALAXY',
    description: 'metus eu erat semper rutrum. Fusce dolor quam, elementum',
  },
  {
    username: 'quis,',
    firstName: 'Brandon',
    lastName: 'Noel',
    email: 'nisi.sem.semper@necanteMaecenas.ca',
    birthDate: '101843690',
    basicSalary: 6255845,
    status: '05',
    group: 'AVENGERS',
    description: 'in molestie',
  },
  {
    username: 'cursus',
    firstName: 'Summer',
    lastName: 'Wall',
    email: 'Curabitur@Integervulputaterisus.com',
    birthDate: '214527331',
    basicSalary: 9797278,
    status: '03',
    group: 'BIRDS OF PREY',
    description: 'vitae odio',
  },
  {
    username: 'ornare',
    firstName: 'Beau',
    lastName: 'Buckner',
    email: 'penatibus.et@necligulaconsectetuer.com',
    birthDate: '867212750',
    basicSalary: 4480641,
    status: '01',
    group: 'LANTERN CORPS',
    description: 'vulputate eu, odio.',
  },
  {
    username: 'eu',
    firstName: 'Reese',
    lastName: 'Humphrey',
    email: 'neque.venenatis@leoVivamus.ca',
    birthDate: '1037050451',
    basicSalary: 994339,
    status: '03',
    group: 'FANTASTIC FOUR',
    description: 'mi felis, adipiscing fringilla,',
  },
  {
    username: 'risus.',
    firstName: 'Arsenio',
    lastName: 'Montoya',
    email: 'lectus.justo.eu@sit.ca',
    birthDate: '488194856',
    basicSalary: 7029250,
    status: '01',
    group: 'AVENGERS',
    description: 'a, malesuada',
  },
  {
    username: 'urna',
    firstName: 'Simon',
    lastName: 'Witt',
    email: 'mauris.blandit.mattis@luctuset.ca',
    birthDate: '687884994',
    basicSalary: 6460398,
    status: '01',
    group: 'GUARDIANS OF GALAXY',
    description: 'feugiat.',
  },
  {
    username: 'auctor,',
    firstName: 'Oprah',
    lastName: 'Boyer',
    email: 'sollicitudin.adipiscing@uteratSed.net',
    birthDate: '482604394',
    basicSalary: 384343,
    status: '04',
    group: 'DEFENDERS',
    description: 'dui nec urna suscipit nonummy. Fusce fermentum fermentum',
  },
  {
    username: 'neque',
    firstName: 'Alexander',
    lastName: 'Mcknight',
    email: 'eget@necorci.edu',
    birthDate: '894125564',
    basicSalary: 1973581,
    status: '01',
    group: 'FANTASTIC FOUR',
    description: 'magna. Phasellus dolor elit, pellentesque a, facilisis non,',
  },
  {
    username: 'fringilla',
    firstName: 'Armand',
    lastName: 'Anthony',
    email: 'Mauris@Cumsociis.org',
    birthDate: '456670225',
    basicSalary: 1935782,
    status: '02',
    group: 'INJUSTICE',
    description: 'Phasellus',
  },
  {
    username: 'viverra.',
    firstName: 'Kennan',
    lastName: 'Benson',
    email: 'Donec.nibh@enimSuspendisse.com',
    birthDate: '844175782',
    basicSalary: 5746613,
    status: '04',
    group: 'FANTASTIC FOUR',
    description: 'Nam ligula elit, pretium et, rutrum non,',
  },
  {
    username: 'libero',
    firstName: 'Finn',
    lastName: 'Mcintosh',
    email: 'Quisque.ac@fermentumrisusat.co.uk',
    birthDate: '799380710',
    basicSalary: 2055539,
    status: '04',
    group: 'AVENGERS',
    description: 'semper.',
  },
  {
    username: 'dolor',
    firstName: 'Keelie',
    lastName: 'Park',
    email: 'nisl.Maecenas@risusDonecnibh.edu',
    birthDate: '271687265',
    basicSalary: 4232118,
    status: '03',
    group: 'BIRDS OF PREY',
    description: 'lectus quis massa. Mauris vestibulum, neque sed',
  },
  {
    username: 'elit,',
    firstName: 'Sean',
    lastName: 'Howell',
    email: 'fermentum@sitametconsectetuer.edu',
    birthDate: '709962099',
    basicSalary: 2920571,
    status: '03',
    group: 'GUARDIANS OF GALAXY',
    description:
      'lorem tristique aliquet. Phasellus fermentum convallis ligula.',
  },
  {
    username: 'adipiscing',
    firstName: 'Anthony',
    lastName: 'Smith',
    email: 'Nullam@imperdietnon.co.uk',
    birthDate: '449328109',
    basicSalary: 6336451,
    status: '04',
    group: 'X-MEN',
    description: 'volutpat',
  },
  {
    username: 'auctor,',
    firstName: 'Clayton',
    lastName: 'Landry',
    email: 'sociis@egetmetus.edu',
    birthDate: '229781136',
    basicSalary: 2864863,
    status: '02',
    group: 'JUSTICE LEAGUE',
    description: 'orci. Donec nibh.',
  },
  {
    username: 'Curae;',
    firstName: 'Uta',
    lastName: 'Britt',
    email: 'et.libero.Proin@accumsan.net',
    birthDate: '916346206',
    basicSalary: 1304748,
    status: '04',
    group: 'AVENGERS',
    description: 'eu sem. Pellentesque ut ipsum ac',
  },
  {
    username: 'neque',
    firstName: 'Uriel',
    lastName: 'Mcgee',
    email: 'auctor.quis.tristique@ac.net',
    birthDate: '324235428',
    basicSalary: 5443926,
    status: '02',
    group: 'BIRDS OF PREY',
    description: 'vitae aliquam eros',
  },
  {
    username: 'quam.',
    firstName: 'Rhiannon',
    lastName: 'Lane',
    email: 'dapibus.rutrum.justo@ipsumnunc.co.uk',
    birthDate: '866135983',
    basicSalary: 5879136,
    status: '03',
    group: 'BIRDS OF PREY',
    description: 'aliquet diam. Sed diam lorem, auctor quis, tristique',
  },
  {
    username: 'cursus,',
    firstName: 'Audra',
    lastName: 'Barnes',
    email: 'fringilla.porttitor@Vestibulumaccumsan.com',
    birthDate: '828108190',
    basicSalary: 278366,
    status: '03',
    group: 'INHUMAN',
    description: 'bibendum fermentum metus. Aenean sed pede nec ante',
  },
  {
    username: 'egestas',
    firstName: 'Martina',
    lastName: 'Kidd',
    email: 'viverra.Donec.tempus@risus.org',
    birthDate: '56705041',
    basicSalary: 6564940,
    status: '01',
    group: 'JUSTICE LEAGUE',
    description: 'mauris ut mi. Duis risus odio,',
  },
  {
    username: 'elit,',
    firstName: 'Aurelia',
    lastName: 'Rhodes',
    email: 'at.velit@Etiamlaoreet.edu',
    birthDate: '594562468',
    basicSalary: 9142978,
    status: '04',
    group: 'FANTASTIC FOUR',
    description: 'a, aliquet vel, vulputate eu,',
  },
  {
    username: 'Nunc',
    firstName: 'Chaim',
    lastName: 'Ingram',
    email: 'quam@etrutrumnon.co.uk',
    birthDate: '529796923',
    basicSalary: 2104371,
    status: '01',
    group: 'DEFENDERS',
    description: 'non enim. Mauris quis turpis',
  },
  {
    username: 'id,',
    firstName: 'Keely',
    lastName: 'Moon',
    email: 'facilisis.facilisis@urnajustofaucibus.org',
    birthDate: '495683280',
    basicSalary: 6748875,
    status: '01',
    group: 'X-MEN',
    description: 'Donec tincidunt. Donec vitae erat vel pede',
  },
  {
    username: 'auctor',
    firstName: 'Norman',
    lastName: 'Beck',
    email: 'tortor@eudui.net',
    birthDate: '457045357',
    basicSalary: 2232035,
    status: '05',
    group: 'AVENGERS',
    description: 'Nunc mauris',
  },
  {
    username: 'ullamcorper.',
    firstName: 'Leah',
    lastName: 'Ashley',
    email: 'nec.imperdiet@Nuncac.com',
    birthDate: '852402534',
    basicSalary: 2542015,
    status: '05',
    group: 'AVENGERS',
    description: 'felis, adipiscing fringilla, porttitor vulputate, posuere',
  },
  {
    username: 'nulla',
    firstName: 'Gwendolyn',
    lastName: 'Blanchard',
    email: 'Nulla.aliquet.Proin@euismodestarcu.ca',
    birthDate: '962057012',
    basicSalary: 9069457,
    status: '01',
    group: 'AVENGERS',
    description: 'scelerisque scelerisque dui. Suspendisse ac metus vitae',
  },
  {
    username: 'pede',
    firstName: 'Macy',
    lastName: 'Mcmillan',
    email: 'In.mi@Donec.co.uk',
    birthDate: '305187733',
    basicSalary: 7049940,
    status: '03',
    group: 'FANTASTIC FOUR',
    description: 'nec tempus mauris erat eget ipsum. Suspendisse',
  },
  {
    username: 'diam',
    firstName: 'Ava',
    lastName: 'Newman',
    email: 'mauris.ut.mi@dignissimtempor.com',
    birthDate: '976585955',
    basicSalary: 5909427,
    status: '05',
    group: 'X-MEN',
    description: 'accumsan laoreet ipsum. Curabitur',
  },
  {
    username: 'mollis',
    firstName: 'Dalton',
    lastName: 'Perez',
    email: 'ullamcorper.Duis@euligula.net',
    birthDate: '783300151',
    basicSalary: 1853588,
    status: '05',
    group: 'INHUMAN',
    description: 'sem semper erat, in consectetuer ipsum nunc id enim.',
  },
  {
    username: 'gravida',
    firstName: 'Teagan',
    lastName: 'Ewing',
    email: 'iaculis@malesuadamalesuada.edu',
    birthDate: '188428960',
    basicSalary: 5020077,
    status: '05',
    group: 'FANTASTIC FOUR',
    description: 'Integer urna. Vivamus molestie',
  },
  {
    username: 'est',
    firstName: 'Nigel',
    lastName: 'Osborn',
    email: 'Quisque.porttitor@adui.com',
    birthDate: '712090649',
    basicSalary: 3371655,
    status: '03',
    group: 'GUARDIANS OF GALAXY',
    description: 'consectetuer euismod est arcu',
  },
  {
    username: 'purus',
    firstName: 'Nathaniel',
    lastName: 'Wolfe',
    email: 'vitae.nibh@adipiscingelit.ca',
    birthDate: '147997037',
    basicSalary: 9966662,
    status: '05',
    group: 'INHUMAN',
    description: 'ligula.',
  },
  {
    username: 'nec',
    firstName: 'Dexter',
    lastName: 'Hawkins',
    email: 'vitae@per.org',
    birthDate: '163425139',
    basicSalary: 8560113,
    status: '02',
    group: 'FANTASTIC FOUR',
    description: 'Aenean eget magna.',
  },
  {
    username: 'mattis.',
    firstName: 'Hakeem',
    lastName: 'Small',
    email: 'fermentum.arcu.Vestibulum@non.ca',
    birthDate: '140890481',
    basicSalary: 51956,
    status: '04',
    group: 'INJUSTICE',
    description: 'a,',
  },
  {
    username: 'lobortis,',
    firstName: 'Pascale',
    lastName: 'Battle',
    email: 'ultrices@lacus.net',
    birthDate: '404466974',
    basicSalary: 3379452,
    status: '04',
    group: 'LANTERN CORPS',
    description: 'faucibus id, libero. Donec consectetuer mauris id sapien.',
  },
  {
    username: 'a',
    firstName: 'Britanni',
    lastName: 'Hurley',
    email: 'Cum.sociis@Loremipsum.com',
    birthDate: '123608190',
    basicSalary: 4906884,
    status: '03',
    group: 'DEFENDERS',
    description: 'vel',
  },
  {
    username: 'eget,',
    firstName: 'Brynne',
    lastName: 'Justice',
    email: 'euismod.in@SedmolestieSed.ca',
    birthDate: '1079606302',
    basicSalary: 7498783,
    status: '02',
    group: 'BIRDS OF PREY',
    description: 'Fusce dolor',
  },
  {
    username: 'consequat',
    firstName: 'Oleg',
    lastName: 'Hewitt',
    email: 'id.mollis.nec@Proin.ca',
    birthDate: '921154397',
    basicSalary: 2835765,
    status: '01',
    group: 'LANTERN CORPS',
    description: 'at lacus.',
  },
  {
    username: 'vel,',
    firstName: 'Rhonda',
    lastName: 'Whitfield',
    email: 'non@ipsum.com',
    birthDate: '887510354',
    basicSalary: 5119359,
    status: '02',
    group: 'DEFENDERS',
    description:
      'penatibus et magnis dis parturient montes, nascetur ridiculus',
  },
  {
    username: 'vitae',
    firstName: 'Conan',
    lastName: 'Dennis',
    email: 'a.tortor.Nunc@at.org',
    birthDate: '637315219',
    basicSalary: 1901921,
    status: '02',
    group: 'INHUMAN',
    description: 'Sed eget lacus. Mauris non dui nec urna suscipit',
  },
  {
    username: 'a',
    firstName: 'Kadeem',
    lastName: 'Branch',
    email: 'tincidunt.tempus.risus@semutcursus.net',
    birthDate: '1111416171',
    basicSalary: 8225809,
    status: '04',
    group: 'FANTASTIC FOUR',
    description: 'In',
  },
  {
    username: 'Sed',
    firstName: 'Audrey',
    lastName: 'Maldonado',
    email: 'Aliquam.nec.enim@egestas.org',
    birthDate: '277768050',
    basicSalary: 7055706,
    status: '04',
    group: 'FANTASTIC FOUR',
    description: 'enim',
  },
  {
    username: 'mus.',
    firstName: 'Daniel',
    lastName: 'Dyer',
    email: 'Nunc@Suspendisse.net',
    birthDate: '635389589',
    basicSalary: 5996062,
    status: '02',
    group: 'BIRDS OF PREY',
    description: 'Quisque tincidunt pede ac urna. Ut tincidunt vehicula',
  },
  {
    username: 'Nunc',
    firstName: 'Aristotle',
    lastName: 'Petty',
    email: 'diam@lacusvarius.edu',
    birthDate: '715944881',
    basicSalary: 9294430,
    status: '05',
    group: 'JUSTICE LEAGUE',
    description: 'fringilla,',
  },
  {
    username: 'at,',
    firstName: 'Tatiana',
    lastName: 'Richards',
    email: 'orci@necleoMorbi.co.uk',
    birthDate: '129525540',
    basicSalary: 7795552,
    status: '04',
    group: 'AVENGERS',
    description: 'vulputate, lacus. Cras interdum. Nunc sollicitudin',
  },
  {
    username: 'porttitor',
    firstName: 'Mona',
    lastName: 'Baker',
    email: 'neque.tellus@nasceturridiculus.edu',
    birthDate: '413776964',
    basicSalary: 649221,
    status: '01',
    group: 'LANTERN CORPS',
    description: 'nibh. Aliquam ornare, libero at auctor ullamcorper,',
  },
  {
    username: 'velit',
    firstName: 'Kadeem',
    lastName: 'Talley',
    email: 'velit@liberoMorbiaccumsan.org',
    birthDate: '92615823',
    basicSalary: 9576282,
    status: '01',
    group: 'JUSTICE LEAGUE',
    description: 'metus vitae velit egestas',
  },
  {
    username: 'Aliquam',
    firstName: 'Barclay',
    lastName: 'Buck',
    email: 'porttitor.eros.nec@enimMaurisquis.co.uk',
    birthDate: '551892128',
    basicSalary: 8090095,
    status: '04',
    group: 'GUARDIANS OF GALAXY',
    description: 'diam at pretium aliquet, metus urna convallis',
  },
  {
    username: 'ipsum',
    firstName: 'Isaiah',
    lastName: 'Collins',
    email: 'pede@nonenim.edu',
    birthDate: '374387069',
    basicSalary: 1077436,
    status: '02',
    group: 'INHUMAN',
    description: 'Fusce aliquet magna a neque. Nullam ut nisi a',
  },
  {
    username: 'quis,',
    firstName: 'Georgia',
    lastName: 'Rogers',
    email: 'nulla.Integer.urna@nibhenim.org',
    birthDate: '242053906',
    basicSalary: 8485361,
    status: '05',
    group: 'BIRDS OF PREY',
    description:
      'lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam',
  },
  {
    username: 'tincidunt.',
    firstName: 'Harrison',
    lastName: 'Barron',
    email: 'quis.diam@diamPellentesque.ca',
    birthDate: '929759236',
    basicSalary: 3772204,
    status: '03',
    group: 'DEFENDERS',
    description: 'risus varius orci,',
  },
  {
    username: 'luctus',
    firstName: 'Signe',
    lastName: 'Whitfield',
    email: 'libero@mattis.edu',
    birthDate: '388339433',
    basicSalary: 3682386,
    status: '02',
    group: 'INJUSTICE',
    description: 'Nam interdum',
  },
  {
    username: 'odio',
    firstName: 'Michelle',
    lastName: 'Chen',
    email: 'nunc.Quisque.ornare@ac.org',
    birthDate: '307437953',
    basicSalary: 878204,
    status: '05',
    group: 'LANTERN CORPS',
    description: 'porttitor scelerisque neque. Nullam',
  },
  {
    username: 'Duis',
    firstName: 'Lacey',
    lastName: 'Calhoun',
    email: 'Cum.sociis@lobortisultricesVivamus.com',
    birthDate: '360292153',
    basicSalary: 4538669,
    status: '05',
    group: 'JUSTICE LEAGUE',
    description: 'Quisque ornare tortor at risus. Nunc',
  },
  {
    username: 'augue,',
    firstName: 'Tamekah',
    lastName: 'Pitts',
    email: 'et.malesuada.fames@sodalesMaurisblandit.ca',
    birthDate: '492373768',
    basicSalary: 7889737,
    status: '02',
    group: 'INJUSTICE',
    description: 'turpis egestas.',
  },
  {
    username: 'Cras',
    firstName: 'Rhoda',
    lastName: 'Schroeder',
    email: 'In.at@luctusCurabitur.edu',
    birthDate: '482897539',
    basicSalary: 8959601,
    status: '05',
    group: 'AVENGERS',
    description: 'et magnis',
  },
  {
    username: 'ligula',
    firstName: 'Sandra',
    lastName: 'Romero',
    email: 'fringilla@nec.net',
    birthDate: '279629497',
    basicSalary: 7485821,
    status: '01',
    group: 'INHUMAN',
    description: 'Cras pellentesque. Sed',
  },
  {
    username: 'dolor',
    firstName: 'Raphael',
    lastName: 'Yates',
    email: 'convallis.in.cursus@dignissim.org',
    birthDate: '1103295770',
    basicSalary: 9669482,
    status: '05',
    group: 'BIRDS OF PREY',
    description: 'Donec est mauris, rhoncus id, mollis nec, cursus a,',
  },
  {
    username: 'Suspendisse',
    firstName: 'Rae',
    lastName: 'Gardner',
    email: 'lorem@parturientmontesnascetur.org',
    birthDate: '313671039',
    basicSalary: 3706148,
    status: '02',
    group: 'BIRDS OF PREY',
    description:
      'dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc',
  },
  {
    username: 'faucibus',
    firstName: 'Dale',
    lastName: 'Sandoval',
    email: 'ut.erat@ametconsectetueradipiscing.co.uk',
    birthDate: '308865477',
    basicSalary: 5472101,
    status: '04',
    group: 'LANTERN CORPS',
    description: 'Curabitur massa. Vestibulum accumsan neque et nunc.',
  },
  {
    username: 'montes,',
    firstName: 'Orli',
    lastName: 'Bullock',
    email: 'Nulla.facilisi.Sed@maurisipsum.ca',
    birthDate: '782383801',
    basicSalary: 731573,
    status: '01',
    group: 'X-MEN',
    description: 'non, cursus non, egestas a,',
  },
  {
    username: 'Nullam',
    firstName: 'Branden',
    lastName: 'Jacobson',
    email: 'lorem@Integer.com',
    birthDate: '379328474',
    basicSalary: 1465479,
    status: '04',
    group: 'AVENGERS',
    description: 'Maecenas iaculis aliquet diam. Sed diam',
  },
  {
    username: 'urna.',
    firstName: 'Dalton',
    lastName: 'Bowman',
    email: 'ornare@interdum.ca',
    birthDate: '693140984',
    basicSalary: 8831276,
    status: '01',
    group: 'AVENGERS',
    description:
      'amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer',
  },
  {
    username: 'ac',
    firstName: 'Abigail',
    lastName: 'Stanton',
    email: 'orci.sem@sodalesnisimagna.edu',
    birthDate: '667843758',
    basicSalary: 7944194,
    status: '02',
    group: 'DEFENDERS',
    description: 'aliquam eros turpis non',
  },
  {
    username: 'metus.',
    firstName: 'Xenos',
    lastName: 'Parrish',
    email: 'justo@orciDonec.ca',
    birthDate: '973734459',
    basicSalary: 3084764,
    status: '04',
    group: 'LANTERN CORPS',
    description:
      'massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus',
  },
  {
    username: 'Sed',
    firstName: 'Katell',
    lastName: 'Macdonald',
    email: 'tristique.pellentesque@parturientmontes.edu',
    birthDate: '615271411',
    basicSalary: 9877719,
    status: '02',
    group: 'INHUMAN',
    description: 'Nunc commodo auctor velit. Aliquam',
  },
  {
    username: 'sem',
    firstName: 'Ahmed',
    lastName: 'Dunlap',
    email: 'dolor.Donec.fringilla@gravida.net',
    birthDate: '642999903',
    basicSalary: 9203663,
    status: '04',
    group: 'BIRDS OF PREY',
    description: 'natoque penatibus et magnis dis parturient montes,',
  },
];
